#!/bin/bash

if [[ -d '/Applications/TrollDebs.app' ]]; then
     uicache -p /Applications/TrollDebs.app
elif [[ -d '/var/jb/Applications/TrollDebs.app' ]]; then
     uicache -p /var/jb/Applications/TrollDebs.app
fi
