name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install needed tools
        run: |
          brew install ldid dpkg
          
      - name: Setup Xcode
        uses: actions/setup-xcode@v4
        with:
          xcode-version: '14.3.1'
          
      - name: Build & Sign Application
        run: |
          make
          
      - name: Upload TrollStore .tipa
        uses: actions/upload-artifact@v4
        with:
          name: TrollDebsTrollstore.tipa
          path: ${{ github.workspace }}/build/TrollDebsTrollstore.tipa
          
      - name: Upload deb for Jailbroken devices
        uses: actions/upload-artifact@v4
        with:
          name: TrollDebs
          path: ${{ github.workspace }}/build/TrollDebs.deb