name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - debug

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Build Environment
      run: |
        echo "Setting up build environment..."
        sudo xcode-select --switch /Applications/Xcode.app
        xcodebuild -version
        brew install ldid dpkg xz cmake ninja wget curl libarchive make || true
        echo "$(brew --prefix)/opt/llvm/bin" >> $GITHUB_PATH

    - name: Install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'

    - name: Build Application
      run: |
        make clean
        make package FINALPACKAGE=1

    - name: Upload TrollStore .tipa
      uses: actions/upload-artifact@v4
      with:
        name: TrollDebsTrollstore.tipa
        path: ${{ github.workspace }}/build/TrollDebsTrollstore.tipa
        if-no-files-found: error
          
    - name: Upload deb Package
      uses: actions/upload-artifact@v4
      with:
        name: TrollDebs
        path: ${{ github.workspace }}/build/TrollDebs.deb
        if-no-files-found: error