name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - debug

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Build Environment
      run: |
        echo "Setting up build environment..."
        xcode-select --install || true
        xcodebuild -version
        brew install ldid || true

    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'

    - name: Build for TrollStore
      run: |
        # Ensure all files are executable
        find . -name "*.sh" -exec chmod +x {} \;
        find . -name "*.command" -exec chmod +x {} \;

        # Copy entitlements to the right location
        cp "${{ github.workspace }}/entitlements.plist" "${{ github.workspace }}/TrollDebs/"

        # Build the app with all necessary flags
        xcodebuild \
          -project "${{ github.workspace }}/TrollDebs.xcodeproj" \
          -scheme TrollDebs \
          -configuration Release \
          -sdk iphoneos \
          -derivedDataPath "${{ github.workspace }}/build" \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGN_ENTITLEMENTS="TrollDebs/entitlements.plist" \
          OTHER_CODE_SIGN_FLAGS="--generate-entitlement-der" \
          PRODUCT_BUNDLE_IDENTIFIER="com.serena.trolldebs" \
          DEVELOPMENT_TEAM="" \
          PROVISIONING_PROFILE_SPECIFIER=""

        # Create Payload directory
        mkdir -p Payload
        cp -r "${{ github.workspace }}/build/Build/Products/Release-iphoneos/TrollDebs.app" Payload/

        # Ensure all executables have proper permissions
        find Payload -type f -exec chmod +x {} \;

        # Copy any additional resources
        cp -r "${{ github.workspace }}/Resources" Payload/TrollDebs.app/ || true
        cp -r "${{ github.workspace }}/Scripts" Payload/TrollDebs.app/ || true
        
        # Copy entitlements to the app bundle
        cp "${{ github.workspace }}/entitlements.plist" "Payload/TrollDebs.app/"

        # Create .ipa
        cd Payload
        zip -r "../TrollDebs.ipa" .
        cd ..

    - name: Upload TrollStore .ipa
      uses: actions/upload-artifact@v4
      with:
        name: TrollDebs-TrollStore.ipa
        path: ${{ github.workspace }}/TrollDebs.ipa
        if-no-files-found: error

    - name: Verify IPA Contents
      run: |
        unzip -l "${{ github.workspace }}/TrollDebs.ipa" || true